[workspace]
resolver = "2"
members = ["crates/qala-liftoscript", "crates/qala-liftoscript-json", "crates/qala-liftoscript-wasm", "crates/qala-liftoscript-ffi"]

[workspace.package]
edition = "2021"
license = "AGPL-3.0-or-later"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
