// Generated by scripts/lucide_to_kotlin.ts from lucide-react. Do not edit; run `deno task gen:android`.
// Lucide is ISC licensed. 11 of these icons are derived from Feather (MIT): chevron-left, chevron-down, ellipsis-vertical, moon, info, check, minus, plus, triangle-alert, clock, x.
// Both licence texts are in app/src/main/assets/licenses/.

package com.qala.design

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.StrokeCap
import androidx.compose.ui.graphics.StrokeJoin
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.PathParser
import androidx.compose.ui.unit.dp

/** A 24 dp Lucide icon: stroke 2, round caps and joins, no fill. The stroke is black; tint it. */
private fun qalaIcon(name: String, vararg paths: String): ImageVector =
    ImageVector.Builder(
        name = name,
        defaultWidth = 24.dp,
        defaultHeight = 24.dp,
        viewportWidth = 24f,
        viewportHeight = 24f,
    ).apply {
        for (d in paths) {
            addPath(
                pathData = PathParser().parsePathString(d).toNodes(),
                stroke = SolidColor(Color.Black),
                strokeLineWidth = 2f,
                strokeLineCap = StrokeCap.Round,
                strokeLineJoin = StrokeJoin.Round,
            )
        }
    }.build()

/** The icons DESIGN.md section 4 lists. Built on first use. */
object QalaIcons {
    /** Lucide `sun`. */
    val Sun: ImageVector by lazy {
        qalaIcon(
            "sun",
            "M 8 12 A 4 4 0 1 0 16 12 A 4 4 0 1 0 8 12 Z",
            "M 12 2 v 2",
            "M 12 20 v 2",
            "m 4.93 4.93 l 1.41 1.41",
            "m 17.66 17.66 l 1.41 1.41",
            "M 2 12 h 2",
            "M 20 12 h 2",
            "m 6.34 17.66 l -1.41 1.41",
            "m 19.07 4.93 l -1.41 1.41",
        )
    }

    /** Lucide `calendar-range`. */
    val CalendarRange: ImageVector by lazy {
        qalaIcon(
            "calendar-range",
            "M 5 3 H 19 A 2 2 0 0 1 21 5 V 19 A 2 2 0 0 1 19 21 H 5 A 2 2 0 0 1 3 19 V 5 A 2 2 0 0 1 5 3 Z",
            "M 16 2 v 3",
            "M 3 9 h 18",
            "M 8 2 v 3",
            "M 17 13 h -6",
            "M 13 17 H 7",
            "M 7 13 h .01",
            "M 17 17 h .01",
        )
    }

    /** Lucide `activity`. */
    val Activity: ImageVector by lazy {
        qalaIcon(
            "activity",
            "M 22 12 h -2.48 a 2 2 0 0 0 -1.93 1.46 l -2.35 8.36 a .25 .25 0 0 1 -.48 0 L 9.24 2.18 a .25 .25 0 0 0 -.48 0 l -2.35 8.36 A 2 2 0 0 1 4.49 12 H 2",
        )
    }

    /** Lucide `trending-up`. */
    val TrendingUp: ImageVector by lazy {
        qalaIcon(
            "trending-up",
            "M 16 7 h 6 v 6",
            "m 22 7 l -8.5 8.5 l -5 -5 L 2 17",
        )
    }

    /** Lucide `message-square-text`. */
    val MessageSquareText: ImageVector by lazy {
        qalaIcon(
            "message-square-text",
            "M 22 17 a 2 2 0 0 1 -2 2 H 6.828 a 2 2 0 0 0 -1.414 .586 l -2.202 2.202 A .71 .71 0 0 1 2 21.286 V 5 a 2 2 0 0 1 2 -2 h 16 a 2 2 0 0 1 2 2 Z",
            "M 7 11 h 10",
            "M 7 15 h 6",
            "M 7 7 h 8",
        )
    }

    /** Lucide `history`. */
    val History: ImageVector by lazy {
        qalaIcon(
            "history",
            "M 3 12 a 9 9 0 1 0 9 -9 a 9.75 9.75 0 0 0 -6.74 2.74 L 3 8",
            "M 3 3 v 5 h 5",
            "M 12 7 v 5 l 4 2",
        )
    }

    /** Lucide `settings`. */
    val Settings: ImageVector by lazy {
        qalaIcon(
            "settings",
            "M 9.671 4.136 a 2.34 2.34 0 0 1 4.659 0 a 2.34 2.34 0 0 0 3.319 1.915 a 2.34 2.34 0 0 1 2.33 4.033 a 2.34 2.34 0 0 0 0 3.831 a 2.34 2.34 0 0 1 -2.33 4.033 a 2.34 2.34 0 0 0 -3.319 1.915 a 2.34 2.34 0 0 1 -4.659 0 a 2.34 2.34 0 0 0 -3.32 -1.915 a 2.34 2.34 0 0 1 -2.33 -4.033 a 2.34 2.34 0 0 0 0 -3.831 A 2.34 2.34 0 0 1 6.35 6.051 a 2.34 2.34 0 0 0 3.319 -1.915",
            "M 9 12 A 3 3 0 1 0 15 12 A 3 3 0 1 0 9 12 Z",
        )
    }

    /** Lucide `chevron-left`. */
    val ChevronLeft: ImageVector by lazy {
        qalaIcon(
            "chevron-left",
            "m 15 18 l -6 -6 l 6 -6",
        )
    }

    /** Lucide `chevron-down`. */
    val ChevronDown: ImageVector by lazy {
        qalaIcon(
            "chevron-down",
            "m 6 9 l 6 6 l 6 -6",
        )
    }

    /** Lucide `ellipsis-vertical`. */
    val EllipsisVertical: ImageVector by lazy {
        qalaIcon(
            "ellipsis-vertical",
            "M 11 12 A 1 1 0 1 0 13 12 A 1 1 0 1 0 11 12 Z",
            "M 11 5 A 1 1 0 1 0 13 5 A 1 1 0 1 0 11 5 Z",
            "M 11 19 A 1 1 0 1 0 13 19 A 1 1 0 1 0 11 19 Z",
        )
    }

    /** Lucide `dumbbell`. */
    val Dumbbell: ImageVector by lazy {
        qalaIcon(
            "dumbbell",
            "M 17.596 12.768 a 2 2 0 1 0 2.829 -2.829 l -1.768 -1.767 a 2 2 0 0 0 2.828 -2.829 l -2.828 -2.828 a 2 2 0 0 0 -2.829 2.828 l -1.767 -1.768 a 2 2 0 1 0 -2.829 2.829 Z",
            "m 2.5 21.5 l 1.4 -1.4",
            "m 20.1 3.9 l 1.4 -1.4",
            "M 5.343 21.485 a 2 2 0 1 0 2.829 -2.828 l 1.767 1.768 a 2 2 0 1 0 2.829 -2.829 l -6.364 -6.364 a 2 2 0 1 0 -2.829 2.829 l 1.768 1.767 a 2 2 0 0 0 -2.828 2.829 Z",
            "m 9.6 14.4 l 4.8 -4.8",
        )
    }

    /** Lucide `sport-shoe`. */
    val SportShoe: ImageVector by lazy {
        qalaIcon(
            "sport-shoe",
            "m 15 10.42 l 4.8 -5.07",
            "M 19 18 h 3",
            "M 9.5 22 L 21.414 9.415 A 2 2 0 0 0 21.2 6.4 l -5.61 -4.208 A 1 1 0 0 0 14 3 v 2 a 2 2 0 0 1 -1.394 1.906 L 8.677 8.053 A 1 1 0 0 0 8 9 c -.155 6.393 -2.082 9 -4 9 a 2 2 0 0 0 0 4 h 14",
        )
    }

    /** Lucide `bed`. */
    val Bed: ImageVector by lazy {
        qalaIcon(
            "bed",
            "M 2 4 v 16",
            "M 2 8 h 18 a 2 2 0 0 1 2 2 v 10",
            "M 2 17 h 20",
            "M 6 8 v 9",
        )
    }

    /** Lucide `circle-check`. */
    val CircleCheck: ImageVector by lazy {
        qalaIcon(
            "circle-check",
            "M 2 12 A 10 10 0 1 0 22 12 A 10 10 0 1 0 2 12 Z",
            "m 16 9 l -5.5 5.5 L 8 12",
        )
    }

    /** Lucide `flame`. */
    val Flame: ImageVector by lazy {
        qalaIcon(
            "flame",
            "M 12 3 q 1 4 4 6.5 t 3 5.5 a 1 1 0 0 1 -14 0 a 5 5 0 0 1 1 -3 a 1 1 0 0 0 5 0 c 0 -2 -1.5 -3 -1.5 -5 q 0 -2 2.5 -4",
        )
    }

    /** Lucide `hourglass`. */
    val Hourglass: ImageVector by lazy {
        qalaIcon(
            "hourglass",
            "M 5 22 h 14",
            "M 5 2 h 14",
            "M 17 22 v -4.172 a 2 2 0 0 0 -.586 -1.414 L 12 12 l -4.414 4.414 A 2 2 0 0 0 7 17.828 V 22",
            "M 7 2 v 4.172 a 2 2 0 0 0 .586 1.414 L 12 12 l 4.414 -4.414 A 2 2 0 0 0 17 6.172 V 2",
        )
    }

    /** Lucide `moon`. */
    val Moon: ImageVector by lazy {
        qalaIcon(
            "moon",
            "M 20.985 12.486 a 9 9 0 1 1 -9.473 -9.472 c .405 -.022 .617 .46 .402 .803 a 6 6 0 0 0 8.268 8.268 c .344 -.215 .825 -.004 .803 .401",
        )
    }

    /** Lucide `info`. */
    val Info: ImageVector by lazy {
        qalaIcon(
            "info",
            "M 2 12 A 10 10 0 1 0 22 12 A 10 10 0 1 0 2 12 Z",
            "M 12 16 v -4",
            "M 12 8 h .01",
        )
    }

    /** Lucide `arrow-left-right`. */
    val ArrowLeftRight: ImageVector by lazy {
        qalaIcon(
            "arrow-left-right",
            "M 8 3 L 4 7 l 4 4",
            "M 4 7 h 16",
            "m 16 21 l 4 -4 l -4 -4",
            "M 20 17 H 4",
        )
    }

    /** Lucide `sticky-note`. */
    val StickyNote: ImageVector by lazy {
        qalaIcon(
            "sticky-note",
            "M 21 9 a 2.4 2.4 0 0 0 -.706 -1.706 l -3.588 -3.588 A 2.4 2.4 0 0 0 15 3 H 5 a 2 2 0 0 0 -2 2 v 14 a 2 2 0 0 0 2 2 h 14 a 2 2 0 0 0 2 -2 Z",
            "M 15 3 v 5 a 1 1 0 0 0 1 1 h 5",
        )
    }

    /** Lucide `pin`. */
    val Pin: ImageVector by lazy {
        qalaIcon(
            "pin",
            "M 12 17 v 5",
            "M 9 10.76 a 2 2 0 0 1 -1.11 1.79 l -1.78 .9 A 2 2 0 0 0 5 15.24 V 16 a 1 1 0 0 0 1 1 h 12 a 1 1 0 0 0 1 -1 v -.76 a 2 2 0 0 0 -1.11 -1.79 l -1.78 -.9 A 2 2 0 0 1 15 10.76 V 7 a 1 1 0 0 1 1 -1 a 2 2 0 0 0 0 -4 H 8 a 2 2 0 0 0 0 4 a 1 1 0 0 1 1 1 Z",
        )
    }

    /** Lucide `check`. */
    val Check: ImageVector by lazy {
        qalaIcon(
            "check",
            "M 20 6 L 9 17 l -5 -5",
        )
    }

    /** Lucide `layout-grid`. */
    val LayoutGrid: ImageVector by lazy {
        qalaIcon(
            "layout-grid",
            "M 4 3 H 9 A 1 1 0 0 1 10 4 V 9 A 1 1 0 0 1 9 10 H 4 A 1 1 0 0 1 3 9 V 4 A 1 1 0 0 1 4 3 Z",
            "M 15 3 H 20 A 1 1 0 0 1 21 4 V 9 A 1 1 0 0 1 20 10 H 15 A 1 1 0 0 1 14 9 V 4 A 1 1 0 0 1 15 3 Z",
            "M 15 14 H 20 A 1 1 0 0 1 21 15 V 20 A 1 1 0 0 1 20 21 H 15 A 1 1 0 0 1 14 20 V 15 A 1 1 0 0 1 15 14 Z",
            "M 4 14 H 9 A 1 1 0 0 1 10 15 V 20 A 1 1 0 0 1 9 21 H 4 A 1 1 0 0 1 3 20 V 15 A 1 1 0 0 1 4 14 Z",
        )
    }

    /** Lucide `calculator`. */
    val Calculator: ImageVector by lazy {
        qalaIcon(
            "calculator",
            "M 6 2 H 18 A 2 2 0 0 1 20 4 V 20 A 2 2 0 0 1 18 22 H 6 A 2 2 0 0 1 4 20 V 4 A 2 2 0 0 1 6 2 Z",
            "M 8 6 L 16 6",
            "M 16 14 L 16 18",
            "M 16 10 h .01",
            "M 12 10 h .01",
            "M 8 10 h .01",
            "M 12 14 h .01",
            "M 8 14 h .01",
            "M 12 18 h .01",
            "M 8 18 h .01",
        )
    }

    /** Lucide `minus`. */
    val Minus: ImageVector by lazy {
        qalaIcon(
            "minus",
            "M 5 12 h 14",
        )
    }

    /** Lucide `plus`. */
    val Plus: ImageVector by lazy {
        qalaIcon(
            "plus",
            "M 5 12 h 14",
            "M 12 5 v 14",
        )
    }

    /** Lucide `triangle-alert`. */
    val TriangleAlert: ImageVector by lazy {
        qalaIcon(
            "triangle-alert",
            "m 21.73 18 l -8 -14 a 2 2 0 0 0 -3.48 0 l -8 14 A 2 2 0 0 0 4 21 h 16 a 2 2 0 0 0 1.73 -3",
            "M 12 9 v 4",
            "M 12 17 h .01",
        )
    }

    /** Lucide `bike`. */
    val Bike: ImageVector by lazy {
        qalaIcon(
            "bike",
            "M 15 17.5 A 3.5 3.5 0 1 0 22 17.5 A 3.5 3.5 0 1 0 15 17.5 Z",
            "M 2 17.5 A 3.5 3.5 0 1 0 9 17.5 A 3.5 3.5 0 1 0 2 17.5 Z",
            "M 14 5 A 1 1 0 1 0 16 5 A 1 1 0 1 0 14 5 Z",
            "M 12 17.5 V 14 l -3 -3 l 4 -3 l 2 3 h 2",
        )
    }

    /** Lucide `play`. */
    val Play: ImageVector by lazy {
        qalaIcon(
            "play",
            "M 5 5 a 2 2 0 0 1 3.008 -1.728 l 11.997 6.998 a 2 2 0 0 1 .003 3.458 l -12 7 A 2 2 0 0 1 5 19 Z",
        )
    }

    /** Lucide `pause`. */
    val Pause: ImageVector by lazy {
        qalaIcon(
            "pause",
            "M 15 3 H 18 A 1 1 0 0 1 19 4 V 20 A 1 1 0 0 1 18 21 H 15 A 1 1 0 0 1 14 20 V 4 A 1 1 0 0 1 15 3 Z",
            "M 6 3 H 9 A 1 1 0 0 1 10 4 V 20 A 1 1 0 0 1 9 21 H 6 A 1 1 0 0 1 5 20 V 4 A 1 1 0 0 1 6 3 Z",
        )
    }

    /** Lucide `route`. */
    val Route: ImageVector by lazy {
        qalaIcon(
            "route",
            "M 3 19 A 3 3 0 1 0 9 19 A 3 3 0 1 0 3 19 Z",
            "M 9 19 h 8.5 a 3.5 3.5 0 0 0 0 -7 h -11 a 3.5 3.5 0 0 1 0 -7 H 15",
            "M 15 5 A 3 3 0 1 0 21 5 A 3 3 0 1 0 15 5 Z",
        )
    }

    /** Lucide `signal-high`. */
    val SignalHigh: ImageVector by lazy {
        qalaIcon(
            "signal-high",
            "M 2 20 h .01",
            "M 7 20 v -4",
            "M 12 20 v -8",
            "M 17 20 V 8",
        )
    }

    /** Lucide `volume-2`. */
    val Volume2: ImageVector by lazy {
        qalaIcon(
            "volume-2",
            "M 11 4.702 a .705 .705 0 0 0 -1.203 -.498 L 6.413 7.587 A 1.4 1.4 0 0 1 5.416 8 H 3 a 1 1 0 0 0 -1 1 v 6 a 1 1 0 0 0 1 1 h 2.416 a 1.4 1.4 0 0 1 .997 .413 l 3.383 3.384 A .705 .705 0 0 0 11 19.298 Z",
            "M 16 9 a 5 5 0 0 1 0 6",
            "M 19.364 18.364 a 9 9 0 0 0 0 -12.728",
        )
    }

    /** Lucide `zap`. */
    val Zap: ImageVector by lazy {
        qalaIcon(
            "zap",
            "M 15.914 4 a 1.5 1.5 0 0 0 -2.474 -1.561 l -9 9 A 1.5 1.5 0 0 0 5.5 14 h 4.002 a .5 .5 0 0 1 .471 .666 L 8.086 20 a 1.5 1.5 0 0 0 2.475 1.56 l 9 -9 A 1.5 1.5 0 0 0 18.5 10 h -3.997 a .5 .5 0 0 1 -.472 -.667 Z",
        )
    }

    /** Lucide `heart-pulse`. */
    val HeartPulse: ImageVector by lazy {
        qalaIcon(
            "heart-pulse",
            "M 2 9.5 a 5.5 5.5 0 0 1 9.591 -3.676 a .56 .56 0 0 0 .818 0 A 5.49 5.49 0 0 1 22 9.5 c 0 2.29 -1.5 4 -3 5.5 l -5.492 5.313 a 2 2 0 0 1 -3 .019 L 5 15 c -1.5 -1.5 -3 -3.2 -3 -5.5",
            "M 3.22 13 H 9.5 l .5 -1 l 2 4.5 l 2 -7 l 1.5 3.5 h 5.27",
        )
    }

    /** Lucide `mountain`. */
    val Mountain: ImageVector by lazy {
        qalaIcon(
            "mountain",
            "m 8 3 l 4 8 l 5 -5 l 5 15 H 2 L 8 3 Z",
        )
    }

    /** Lucide `timer`. */
    val Timer: ImageVector by lazy {
        qalaIcon(
            "timer",
            "M 10 2 L 14 2",
            "M 12 14 L 15 11",
            "M 4 14 A 8 8 0 1 0 20 14 A 8 8 0 1 0 4 14 Z",
        )
    }

    /** Lucide `gauge`. */
    val Gauge: ImageVector by lazy {
        qalaIcon(
            "gauge",
            "m 12 14 l 4 -4",
            "M 3.34 19 a 10 10 0 1 1 17.32 0",
        )
    }

    /** Lucide `list-checks`. */
    val ListChecks: ImageVector by lazy {
        qalaIcon(
            "list-checks",
            "M 13 5 h 8",
            "M 13 12 h 8",
            "M 13 19 h 8",
            "m 3 17 l 2 2 l 4 -4",
            "m 3 7 l 2 2 l 4 -4",
        )
    }

    /** Lucide `clock`. */
    val Clock: ImageVector by lazy {
        qalaIcon(
            "clock",
            "M 2 12 A 10 10 0 1 0 22 12 A 10 10 0 1 0 2 12 Z",
            "M 12 6 v 6 l 4 2",
        )
    }

    /** Lucide `x`. */
    val X: ImageVector by lazy {
        qalaIcon(
            "x",
            "M 18 6 L 6 18",
            "m 6 6 l 12 12",
        )
    }
}
