// Generated by scripts/tokens_to_kotlin.ts from apps/web/src/theme/tokens.css. Do not edit; run `deno task gen:android`.

package com.qala.design

import androidx.compose.animation.core.CubicBezierEasing
import androidx.compose.animation.core.Easing
import androidx.compose.runtime.Immutable
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp

/**
 * A Beamer shadow: a hard offset with no blur, plus an optional ring drawn
 * outside the box ([ringWidth] is 0.dp and [ringColor] transparent when there
 * is none). Elevation and blur are never used.
 */
@Immutable
data class QalaShadow(
    val dx: Dp,
    val dy: Dp,
    val color: Color,
    val ringWidth: Dp,
    val ringColor: Color,
)

/** Every colour and shadow token of tokens.css for one theme. Dark is light with the dark overrides applied. */
@Immutable
data class QalaPalette(
    val bg: Color,
    val bgSurface: Color,
    val bgHover: Color,
    val bgActive: Color,
    val bgRecessed: Color,
    val fg: Color,
    val fgSecondary: Color,
    val fgMuted: Color,
    val fgFaint: Color,
    val border: Color,
    val borderStrong: Color,
    val grid: Color,
    val accent: Color,
    val accentHover: Color,
    val accentSubtle: Color,
    val onAccent: Color,
    val run: Color,
    val progress: Color,
    val progressFill: Color,
    val danger: Color,
    val success: Color,
    val zone1: Color,
    val zone2: Color,
    val zone3: Color,
    val zone4: Color,
    val zone5: Color,
    val note: Color,
    val noteBorder: Color,
    val noteInk: Color,
    val rec0: Color,
    val rec1: Color,
    val rec2: Color,
    val rec3: Color,
    val rec4: Color,
    val rec5: Color,
    val viz1: Color,
    val viz2: Color,
    val viz3: Color,
    val int1: Color,
    val int2: Color,
    val int3: Color,
    val int4: Color,
    val int5: Color,
    val markGray: Color,
    val lowZone: Color,
    val bar: Color,
    val barCollar: Color,
    val shadowCard: QalaShadow,
    val shadowCta: QalaShadow,
    val shadowModal: QalaShadow,
) {
    companion object {
        val Light = QalaPalette(
            bg = Color(0xFFF5F5F7),
            bgSurface = Color(0xFFFFFFFF),
            bgHover = Color(0xFFF1F3F9),
            bgActive = Color(0xFFE8EBF4),
            bgRecessed = Color(0xFFF1F3F9),
            fg = Color(0xFF0F152A),
            fgSecondary = Color(0xFF4A5578),
            fgMuted = Color(0xFF64708B),
            fgFaint = Color(0xFF94A0B8),
            border = Color(15, 21, 42, 26),
            borderStrong = Color(15, 21, 42, 56),
            grid = Color(0xFFE3E6EE),
            accent = Color(0xFFC2410C),
            accentHover = Color(0xFF9A3412),
            accentSubtle = Color(194, 65, 12, 20),
            onAccent = Color(0xFFFFFFFF),
            run = Color(0xFF485CC7),
            progress = Color(0xFF0A8078),
            progressFill = Color(0xFF08A49C),
            danger = Color(0xFFB91C1C),
            success = Color(0xFF15803D),
            zone1 = Color(0xFF3A4A9F),
            zone2 = Color(0xFF08A49C),
            zone3 = Color(0xFFE5C73A),
            zone4 = Color(0xFFFB923C),
            zone5 = Color(0xFFC2410C),
            note = Color(0xFFFFF7E6),
            noteBorder = Color(180, 110, 0, 71),
            noteInk = Color(0xFF8A5A00),
            rec0 = Color(0xFF08A49C),
            rec1 = Color(0xFF7FB23A),
            rec2 = Color(0xFFD4B020),
            rec3 = Color(0xFFE08A1E),
            rec4 = Color(0xFFD4551A),
            rec5 = Color(0xFFB3261E),
            viz1 = Color(0xFFC2410C),
            viz2 = Color(0xFF485CC7),
            viz3 = Color(0xFF08A49C),
            int1 = Color(0xFF86B6EF),
            int2 = Color(0xFF5598E7),
            int3 = Color(0xFF2A78D6),
            int4 = Color(0xFF1C5CAB),
            int5 = Color(0xFF104281),
            markGray = Color(0xFFC9CED9),
            lowZone = Color(185, 28, 28, 87),
            bar = Color(0xFF9AA1AD),
            barCollar = Color(0xFF6B7280),
            shadowCard = QalaShadow(dx = 2.dp, dy = 4.dp, color = Color(15, 21, 42, 26), ringWidth = 0.dp, ringColor = Color.Transparent),
            shadowCta = QalaShadow(dx = 2.dp, dy = 4.dp, color = Color(0xFF4A4A4A), ringWidth = 1.dp, ringColor = Color(0xFFC2410C)),
            shadowModal = QalaShadow(dx = 4.dp, dy = 8.dp, color = Color(15, 21, 42, 31), ringWidth = 2.dp, ringColor = Color(15, 21, 42, 26)),
        )

        val Dark = QalaPalette(
            bg = Color(0xFF0B1020),
            bgSurface = Color(0xFF121A33),
            bgHover = Color(0xFF18213F),
            bgActive = Color(0xFF1F2A4D),
            bgRecessed = Color(0xFF0F1529),
            fg = Color(0xFFE8ECF6),
            fgSecondary = Color(0xFFAAB4CC),
            fgMuted = Color(0xFF8A93AB),
            fgFaint = Color(0xFF5D6680),
            border = Color(232, 236, 246, 31),
            borderStrong = Color(232, 236, 246, 61),
            grid = Color(0xFF232C4A),
            accent = Color(0xFFFB923C),
            accentHover = Color(0xFFFDBA74),
            accentSubtle = Color(251, 146, 60, 31),
            onAccent = Color(0xFF0B1020),
            run = Color(0xFF8E9CF0),
            progress = Color(0xFF2DD4BF),
            progressFill = Color(0xFF2DD4BF),
            danger = Color(0xFFF87171),
            success = Color(0xFF4ADE80),
            zone1 = Color(0xFF3A4A9F),
            zone2 = Color(0xFF08A49C),
            zone3 = Color(0xFFE5C73A),
            zone4 = Color(0xFFFB923C),
            zone5 = Color(0xFFC2410C),
            note = Color(0xFF2A2412),
            noteBorder = Color(251, 191, 36, 77),
            noteInk = Color(0xFFFBBF24),
            rec0 = Color(0xFF16A390),
            rec1 = Color(0xFF8CC24A),
            rec2 = Color(0xFFE0C13A),
            rec3 = Color(0xFFEE9A35),
            rec4 = Color(0xFFE8663A),
            rec5 = Color(0xFFD9453C),
            viz1 = Color(0xFFE0652B),
            viz2 = Color(0xFF6F80E6),
            viz3 = Color(0xFF16A390),
            int1 = Color(0xFF184F95),
            int2 = Color(0xFF256ABF),
            int3 = Color(0xFF3987E5),
            int4 = Color(0xFF6DA7EC),
            int5 = Color(0xFF9EC5F4),
            markGray = Color(0xFF39425F),
            lowZone = Color(248, 113, 113, 102),
            bar = Color(0xFF6B7384),
            barCollar = Color(0xFF9AA1AD),
            shadowCard = QalaShadow(dx = 2.dp, dy = 4.dp, color = Color(0xFF2A3350), ringWidth = 0.dp, ringColor = Color.Transparent),
            shadowCta = QalaShadow(dx = 2.dp, dy = 4.dp, color = Color(0xFF3A4466), ringWidth = 1.dp, ringColor = Color(0xFFFB923C)),
            shadowModal = QalaShadow(dx = 4.dp, dy = 8.dp, color = Color(0xFF2A3350), ringWidth = 2.dp, ringColor = Color(232, 236, 246, 31)),
        )
    }
}

/** Theme-independent shape, spacing and motion tokens. Durations are milliseconds. */
object QalaTokens {
    val radius: Dp = 4.dp
    val radiusMd: Dp = 6.dp
    val radiusLg: Dp = 8.dp
    val borderWidth: Dp = 2.dp
    val space1: Dp = 4.dp
    val space2: Dp = 8.dp
    val space3: Dp = 12.dp
    val space4: Dp = 16.dp
    val space5: Dp = 24.dp
    val space6: Dp = 32.dp
    val space7: Dp = 48.dp
    const val durationFast = 150
    const val duration = 200
    val ease: Easing = CubicBezierEasing(0.25f, 1f, 0.5f, 1f)
}
