#!/usr/bin/env python3
"""Turn liftosaur's positioned body artwork into a data module the web app
can draw and colour per muscle.

    python3 scripts/build-bodymap.py

The repo's front-muscles.svg / back-muscles.svg are defs only: the offset of
every muscle lives in liftosaur's React components, vendored unchanged in
packages/liftoscript/images/upstream/ (AGPL-3.0, credited in NOTICE). This
reads those, flattens each muscle into translated path groups, and writes
apps/web/src/shared/bodymap/data.ts. Re-run after refreshing upstream."""
import json, re, pathlib

root = pathlib.Path(__file__).resolve().parent.parent
up = root / "packages/liftoscript/images/upstream"
out = root / "apps/web/src/shared/bodymap/data.ts"

TOKEN = re.compile(r'<G\b([^>]*)>|</G>|<Path\s+d="([^"]*)"', re.S)


def parse(tsx):
    stack = [("", 0.0, 0.0)]  # (muscle id, tx, ty), translates accumulate
    groups = {}  # muscle -> [ {tx, ty, paths} ]
    cur = {}  # (muscle, tx, ty) -> group
    for m in TOKEN.finditer(tsx):
        if m.group(0) == "</G>":
            stack.pop()
        elif m.group(0).startswith("<G"):
            attrs = m.group(1)
            mid, tx, ty = stack[-1]
            name = re.search(r'getFill\("(\w+)"\)', attrs)
            if name:
                mid = name.group(1)
            elif "props.contour" in attrs:
                mid = "contour"
            t = re.search(r'translate\(([^)]*)\)', attrs)
            if t:
                dx, dy = [float(v) for v in re.split(r"[ ,]+", t.group(1).strip())]
                tx, ty = tx + dx, ty + dy
            stack.append((mid, tx, ty))
        else:
            mid, tx, ty = stack[-1]
            if not mid:
                continue
            key = (mid, round(tx, 6), round(ty, 6))
            if key not in cur:
                cur[key] = {"tx": key[1], "ty": key[2], "paths": []}
                groups.setdefault(mid, []).append(cur[key])
            cur[key]["paths"].append(m.group(2))
    return [{"id": k, "groups": v} for k, v in groups.items()]


NUM = re.compile(r"-?\d+(?:\.\d+)?(?:e-?\d+)?")


def path_box(d, tx, ty):
    n = [float(v) for v in NUM.findall(d)]
    xs, ys = n[0::2], n[1::2]
    return min(xs) + tx, min(ys) + ty, max(xs) + tx, max(ys) + ty


def anchors(part, mid_x):
    """Centre of the biggest path on each side of the body, for leader lines.
    Returns {"l": [x, y], "r": [x, y]}; a side with no path reuses the other."""
    best = {}
    for g in part["groups"]:
        for d in g["paths"]:
            x0, y0, x1, y1 = path_box(d, g["tx"], g["ty"])
            cx, cy, area = (x0 + x1) / 2, (y0 + y1) / 2, (x1 - x0) * (y1 - y0)
            side = "l" if cx < mid_x else "r"
            if side not in best or area > best[side][2]:
                best[side] = (round(cx, 1), round(cy, 1), area)
    out = {k: [v[0], v[1]] for k, v in best.items()}
    for k, o in (("l", "r"), ("r", "l")):
        out.setdefault(k, out[o])
    return out


views = {}
for name in ("front", "back"):
    tsx = (up / f"{name}MusclesSvg.tsx").read_text()
    vb = re.search(r'viewBox="([^"]+)"', tsx).group(1)
    parts = parse(tsx)
    for part in parts:
        if part["id"] != "contour":
            part["anchors"] = anchors(part, 56.0)
    views[name] = {"viewBox": vb, "parts": parts}

out.write_text(
    "/* Generated by scripts/build-bodymap.py from liftosaur's body artwork\n"
    " * (AGPL-3.0). Do not edit by hand. Part ids are liftosaur's screen\n"
    " * muscles plus \"contour\", the outline. */\n\n"
    "export interface BodyGroup {\n  tx: number;\n  ty: number;\n  paths: string[];\n}\n"
    "export interface BodyPart {\n  id: string;\n  groups: BodyGroup[];\n  /** Leader-line targets, viewer's left and right. Not on the contour. */\n  anchors?: { l: [number, number]; r: [number, number] };\n}\n"
    "export interface BodyView {\n  viewBox: string;\n  parts: BodyPart[];\n}\n\n"
    f"export const BODY: Record<\"front\" | \"back\", BodyView> = {json.dumps(views)};\n"
)
for k, v in views.items():
    print(k, v["viewBox"], [(p["id"], sum(len(g["paths"]) for g in p["groups"])) for p in v["parts"]])
