// Hand-written liftoscript snippets covering every construct in
// packages/liftoscript/liftoscript.grammar. Only parsed, never evaluated, so
// some are deliberately not valid programs (the Lezer error node is part of
// what the Rust parser must reproduce).
export const EXTRA_SCRIPTS: string[] = [
  // numbers and units
  "1",
  "12.5",
  ".5",
  "5.",
  "1.2.3",
  "+5",
  "-5",
  "- 5",
  "100lb",
  "62.5kg",
  "-2.5kg",
  "75%",
  "12.5%",
  // operators and precedence
  "1 + 2",
  "1 - 2",
  "1 * 2",
  "1 / 2",
  "7 % 3",
  "1 + 2 * 3",
  "1 * 2 + 3",
  "1 - 2 - 3",
  "8 / 4 / 2",
  "1 + 2 > 3 && 4 < 5 || 6 == 7",
  "1 < 2 && 2 <= 3 && 3 > 2 && 3 >= 3 && 1 != 2",
  "1 || 0 && 0",
  "(1 + 2) * 3",
  "((1))",
  "!1",
  "!(1 > 2)",
  "!!1",
  "!x && y",
  "-x",
  "1 - -2",
  "5 * -2",
  // ternary
  "1 ? 2 : 3",
  "a ? b : c ? d : e",
  "a > b ? a : b",
  "(a ? b : c) + 1",
  "a ? b ? 1 : 2 : 3",
  // variables, assignments
  "var.x = 5",
  "var.x = var.y + 1",
  "state.weight = 100lb",
  "state.reps += 1",
  "state.weight -= 5lb",
  "state.weight *= 1.1",
  "state.weight /= 2",
  "var.a += 1",
  "var.a = var.b = 3",
  "state.a = state.b = state.c",
  "weights[1] = 100lb",
  "weights[*] = 100lb",
  "weights[1:3] = 5",
  "reps[1:*] += 1",
  "weights[*:*:*] = 0",
  "weights[var.i + 1] = completedWeights[var.i]",
  "state[1].weight = 10",
  "state[var.i + 1].weight += 5lb",
  "state[ 2 ].x",
  "weights",
  "completedReps[1]",
  "completedReps[*]",
  // builtin functions
  "sum(completedReps)",
  "min(1, 2)",
  "max(1, 2, 3)",
  "floor(var.x / 2)",
  "rm1()",
  "round(state.weight)",
  "sum(completedReps[*]) + 1",
  "print(1, 2)",
  "roundWeight(weights[1])",
  "calculateTrainingMax(1, 2, 3)",
  // control flow
  "if (1) { 2 }",
  "if (completedReps >= reps) { state.weight += 5lb }",
  "if (1) { 2 } else { 3 }",
  "if (1) { 2 } else if (3) { 4 }",
  "if (1) { 2 } else if (3) { 4 } else if (5) { 6 } else { 7 }",
  "if (a) { if (b) { 1 } else { 2 } } else { 3 }",
  "for (var.i in completedReps) { var.x += var.i }",
  "for (var.s in weights) { if (var.s > 100lb) { state.heavy = 1 } }",
  "for (var.i in sum(1, 2)) { for (var.j in completedReps) { var.k += 1 } }",
  "{ 1 2 3 }",
  "{ }",
  "{ { { 1 } } }",
  // comments, separators, skipped tokens
  "// just a comment",
  "1 + 2 // trailing",
  "var.x = 1 // first\nvar.y = 2 // second\n",
  "{~ state.weight += 5lb ~}",
  "var.x = 1; var.y = 2;",
  "var.x = 1\nvar.y = 2\nvar.z = var.x * var.y",
  "  \n\t  1  \n",
  "",
  // realistic progression scripts
  "if (completedReps >= reps) {\n  state.weight += 5lb\n} else {\n  state.weight -= 10%\n}",
  "var.total = sum(completedReps)\nif (var.total >= 25) { weights = weights[1] + 5lb }",
  "state.stage == 1 && !(completedReps >= reps) ? state.stage = 2 : 0",
  "for (var.i in completedReps) {\n  if (completedReps[var.i] < reps[var.i]) {\n    state.failed = 1\n  }\n}",
  "rpe[*] = 8 + 0.5\ntimer[*] = 180",
  "weights[*] = state.weight * 85%",
  // error recovery
  "1 +",
  "(1",
  "1 2 )",
  "if (1) 2",
  "var. = 1",
  "state.",
  "a ? b",
  "@#",
  "1 = 2",
];
